import { ActionTemplate } from "./types";

export const ACTION_TEMPLATES: ActionTemplate[] = [
  {
    key: "plan_screen_free_activity_daily",
    domain: "media_balance",
    title: "Plan one screen-free family activity each day",
    description: "Create a daily offline activity that the family can enjoy together.",
    ageBands: ["0-5", "6-12", "13-18"],
    goals: ["increase_offline_play", "family_connection", "reduce_screen_time"],
    weight: 8,
    isCore: true,
    tags: ["offline", "routine"],
  },
  {
    key: "track_screen_use_patterns",
    domain: "media_balance",
    title: "Track which media activities are taking up too much time",
    description: "Notice where time is going so you can make more intentional choices.",
    ageBands: ["6-12", "13-18"],
    concerns: ["addiction", "attention"],
    goals: ["reduce_screen_time", "improve_focus"],
    weight: 7,
    tags: ["awareness"],
  },
  {
    key: "turn_off_unused_media",
    domain: "media_balance",
    title: "Turn off media that nobody is actively using",
    description: "Reduce background media and passive exposure.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["attention", "content_quality"],
    weight: 6,
    isCore: true,
  },
  {
    key: "reduce_number_of_apps",
    domain: "media_balance",
    title: "Keep fewer apps on family devices",
    description: "Reduce clutter, temptation, and unnecessary notifications.",
    ageBands: ["6-12", "13-18"],
    concerns: ["addiction", "attention"],
    triggers: ["has_personal_device"],
    weight: 7,
  },
  {
    key: "set_lock_screen_reminders",
    domain: "media_balance",
    title: "Use lock-screen reminders or timers",
    description: "Use visual reminders to make stopping easier.",
    ageBands: ["6-12", "13-18"],
    concerns: ["addiction"],
    weight: 6,
  },
  {
    key: "turn_off_autoplay_and_endless_feeds",
    domain: "media_balance",
    title: "Turn off autoplay and reduce endless-scroll feeds",
    description: "Remove design features that keep pulling the child back in.",
    ageBands: ["6-12", "13-18"],
    concerns: ["addiction", "attention", "social_media"],
    usageTypes: ["short_video", "social_media"],
    triggers: ["autoplay_or_endless_scroll"],
    goals: ["reduce_screen_time", "improve_focus"],
    weight: 9,
    isCore: true,
    tags: ["design", "autoplay", "algorithm"],
  },
  {
    key: "set_media_time_limits",
    domain: "media_balance",
    title: "Set clear media time limits",
    description: "Use predictable boundaries for entertainment media.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["sleep", "addiction", "attention"],
    goals: ["reduce_screen_time", "sleep_better"],
    weight: 9,
    isCore: true,
  },
  {
    key: "prevent_screen_from_interrupting_activity_eating",
    domain: "media_balance",
    title: "Make sure media does not interfere with physical activity and healthy eating",
    description: "Protect movement, meals, and real-world routines.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["attention"],
    goals: ["increase_offline_play"],
    weight: 8,
  },
  {
    key: "prevent_unhealthy_gaming_habits",
    domain: "media_balance",
    title: "Prevent unhealthy gaming habits",
    description: "Set boundaries around gaming duration, spending, and emotional spillover.",
    ageBands: ["6-12", "13-18"],
    concerns: ["gaming", "addiction", "overspending"],
    usageTypes: ["gaming"],
    weight: 8,
  },
  {
    key: "find_healthier_ways_to_cope",
    domain: "media_balance",
    title: "Notice when media is used to dull emotions and find healthier ways to cope",
    description: "Reduce dependence on screens for emotional regulation.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["emotion", "addiction"],
    triggers: ["uses_screen_for_calming"],
    weight: 10,
    isCore: true,
  },
  {
    key: "be_intentional_first_device",
    domain: "media_balance",
    title: "Be intentional about when to give a child or teen a personal device",
    description: "Delay personal devices until the child is ready and support is in place.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety", "social_media", "addiction"],
    triggers: ["has_personal_device"],
    weight: 7,
  },
  {
    key: "talk_about_media_regularly",
    domain: "communication",
    title: "Talk about media on a regular basis",
    description: "Make media an everyday conversation topic rather than a taboo topic.",
    ageBands: ["0-5", "6-12", "13-18"],
    goals: ["safer_media_use", "better_content", "family_connection"],
    weight: 8,
    isCore: true,
  },
  {
    key: "discuss_upsetting_content",
    domain: "communication",
    title: "Discuss media content that is shocking or upsetting",
    description: "Help children process what they see online.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety", "content_quality", "emotion"],
    weight: 8,
  },
  {
    key: "listen_openly",
    domain: "communication",
    title: "Listen to each other with open minds",
    description: "Keep communication nonjudgmental so children are more likely to share.",
    ageBands: ["6-12", "13-18"],
    goals: ["family_connection"],
    weight: 6,
  },
  {
    key: "use_talk_out_louds",
    domain: "communication",
    title: "Use talk-out-louds to teach children how to think about media",
    description: "Model how to question, reflect on, and evaluate media.",
    ageBands: ["0-5", "6-12"],
    goals: ["better_content", "improve_focus"],
    weight: 7,
  },
  {
    key: "recognize_ads_and_motives",
    domain: "communication",
    title: "Teach children how to recognize ads and persuasive motives",
    description: "Help them identify when content is trying to sell, persuade, or manipulate.",
    ageBands: ["6-12", "13-18"],
    concerns: ["content_quality", "overspending"],
    weight: 7,
  },
  {
    key: "check_sources_and_fact_patterns",
    domain: "communication",
    title: "Check sources, motives, and whether information is trustworthy",
    description: "Practice asking who made the content, why it was made, and how to verify it.",
    ageBands: ["6-12", "13-18"],
    concerns: ["content_quality", "social_media"],
    usageTypes: ["short_video", "social_media", "mixed"],
    goals: ["better_content", "safer_media_use"],
    weight: 7,
    tags: ["media-literacy", "misinformation"],
  },
  {
    key: "talk_about_mental_health_effects",
    domain: "communication",
    title: "Talk about how media can affect emotions and mental health",
    description: "Normalize discussions about stress, comparison, fear, and overload.",
    ageBands: ["6-12", "13-18"],
    concerns: ["emotion", "social_media"],
    weight: 8,
  },
  {
    key: "respect_online_and_offline",
    domain: "kindness",
    title: "Respect others online and offline",
    description: "Set clear expectations for kindness and respect across settings.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety"],
    weight: 6,
  },
  {
    key: "plan_for_cyberbullying",
    domain: "kindness",
    title: "Have a plan for how to respond to cyberbullying",
    description: "Make sure the child knows what to do, who to tell, and how to save evidence.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety", "social_media"],
    weight: 8,
  },
  {
    key: "be_polite_considerate",
    domain: "kindness",
    title: "Practice being polite and considerate online and in person",
    description: "Help children bring prosocial behavior into digital spaces.",
    ageBands: ["0-5", "6-12", "13-18"],
    weight: 5,
  },
  {
    key: "avoid_oversharing",
    domain: "safety",
    title: "Avoid oversharing personal information",
    description: "Teach children to protect identifying details and location clues.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety", "social_media"],
    weight: 8,
    isCore: true,
  },
  {
    key: "discuss_rabbit_holes_and_bad_content",
    domain: "safety",
    title: "Talk about rabbit holes, inappropriate content, and risky recommendations",
    description: "Prepare children for algorithmic drift toward harmful or unsuitable material.",
    ageBands: ["6-12", "13-18"],
    concerns: ["content_quality", "safety", "social_media"],
    usageTypes: ["short_video", "social_media"],
    weight: 9,
  },
  {
    key: "limit_young_child_media_for_development",
    domain: "safety",
    title: "Limit media use for young children so it does not interfere with development",
    description: "Protect language, sleep, social-emotional growth, and play.",
    ageBands: ["0-5"],
    concerns: ["sleep", "attention", "emotion"],
    weight: 10,
    isCore: true,
  },
  {
    key: "maximize_privacy_settings",
    domain: "safety",
    title: "Set privacy settings to the highest appropriate level",
    description: "Use safe defaults on apps, devices, and accounts.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety", "social_media"],
    triggers: ["has_personal_device"],
    weight: 8,
    isCore: true,
  },
  {
    key: "good_digital_citizenship",
    domain: "safety",
    title: "Talk about what it means to be a good digital citizen",
    description: "Connect online behavior with ethics, responsibility, and community.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety"],
    weight: 6,
  },
  {
    key: "rules_for_online_chat_contacts",
    domain: "safety",
    title: "Set rules for who the child may chat with online",
    description: "Reduce unwanted contact and reinforce boundaries.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety"],
    weight: 8,
  },
  {
    key: "review_reporting_blocking_and_feed_reset",
    domain: "safety",
    title: "Practice blocking, reporting, and resetting unhealthy feeds",
    description: "Make sure the child knows how to leave, report, and reset harmful recommendations.",
    ageBands: ["6-12", "13-18"],
    concerns: ["safety", "social_media", "emotion"],
    usageTypes: ["short_video", "social_media"],
    triggers: ["autoplay_or_endless_scroll", "stranger_contact"],
    goals: ["safer_media_use"],
    weight: 9,
    isCore: true,
    tags: ["algorithm", "reporting", "safety"],
  },
  {
    key: "use_parental_controls_and_account_guardrails",
    domain: "safety",
    title: "Use parental controls for downloads, contacts, purchases, and privacy",
    description: "Set guardrails at the device and account level instead of relying on willpower alone.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["safety", "overspending", "social_media"],
    triggers: ["has_personal_device", "stranger_contact"],
    goals: ["safer_media_use"],
    weight: 9,
    isCore: true,
    tags: ["privacy", "parental-controls"],
  },
  {
    key: "screen_free_meals",
    domain: "screen_zone",
    title: "Keep meals screen-free",
    description: "Protect conversation, routine, and mindful eating.",
    ageBands: ["0-5", "6-12", "13-18"],
    goals: ["family_connection", "reduce_screen_time"],
    weight: 8,
    isCore: true,
  },
  {
    key: "bedroom_screen_free_at_night",
    domain: "screen_zone",
    title: "Keep bedrooms screen-free at night",
    description: "Reduce sleep disruption and late-night use.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["sleep", "addiction"],
    triggers: ["device_in_bedroom"],
    weight: 10,
    isCore: true,
  },
  {
    key: "no_devices_to_from_school",
    domain: "screen_zone",
    title: "Avoid using devices on the way to and from school when possible",
    description: "Create pockets of reflection, conversation, or observation.",
    ageBands: ["6-12", "13-18"],
    concerns: ["addiction", "attention"],
    weight: 6,
  },
  {
    key: "delay_social_media_until_13",
    domain: "screen_zone",
    title: "Hold off on social media until age 13 or later, with parent support",
    description: "Delay access until the child has stronger readiness and supervision.",
    ageBands: ["0-5", "6-12"],
    concerns: ["social_media", "safety", "emotion"],
    weight: 9,
  },
  {
    key: "choose_ok_screen_days",
    domain: "screen_time",
    title: "Choose which days of the week are okay for entertainment screens",
    description: "Create predictable boundaries for weekdays and weekends.",
    ageBands: ["6-12", "13-18"],
    concerns: ["addiction"],
    weight: 6,
  },
  {
    key: "homework_and_screens_plan",
    domain: "screen_time",
    title: "Have a homework-and-screens plan",
    description: "Decide what happens before, during, and after homework.",
    ageBands: ["6-12", "13-18"],
    concerns: ["attention"],
    goals: ["improve_focus"],
    weight: 8,
  },
  {
    key: "use_focus_modes_for_school_and_sleep",
    domain: "screen_time",
    title: "Use do-not-disturb or focus modes for schoolwork, family time, and sleep",
    description: "Silence notifications during the times when the child needs to focus or rest.",
    ageBands: ["6-12", "13-18"],
    concerns: ["attention", "sleep", "social_media"],
    triggers: ["notifications_disrupt", "has_personal_device"],
    goals: ["improve_focus", "sleep_better", "family_connection"],
    weight: 9,
    isCore: true,
    tags: ["notifications", "sleep", "focus"],
  },
  {
    key: "one_screen_at_a_time",
    domain: "screen_time",
    title: "Use only one screen at a time",
    description: "Reduce media multitasking and overload.",
    ageBands: ["6-12", "13-18"],
    concerns: ["attention", "addiction"],
    weight: 8,
  },
  {
    key: "avoid_screens_before_school",
    domain: "screen_time",
    title: "Avoid screens before school",
    description: "Protect morning routines, attention, and readiness.",
    ageBands: ["6-12", "13-18"],
    concerns: ["attention", "sleep"],
    weight: 8,
  },
  {
    key: "screen_free_day_each_week",
    domain: "screen_time",
    title: "Plan one screen-light or screen-free day each week",
    description: "Create a weekly reset and make room for offline life.",
    ageBands: ["0-5", "6-12", "13-18"],
    goals: ["increase_offline_play", "reduce_screen_time"],
    weight: 7,
  },
  {
    key: "silence_phones_family_time",
    domain: "screen_time",
    title: "Use do-not-disturb during family time and playtime",
    description: "Protect presence and reduce interruptions.",
    ageBands: ["6-12", "13-18"],
    goals: ["family_connection"],
    weight: 7,
  },
  {
    key: "prevent_media_interfering_sleep",
    domain: "screen_time",
    title: "Prevent media use from interfering with sleep",
    description: "Align media habits with the child’s sleep schedule and recovery.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["sleep"],
    weight: 10,
    isCore: true,
  },
  {
    key: "avoid_screens_one_hour_before_sleep",
    domain: "screen_time",
    title: "Avoid screens during the hour before sleep",
    description: "Create a calmer pre-sleep routine.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["sleep", "addiction"],
    weight: 10,
    isCore: true,
  },
  {
    key: "be_intentional_about_media_use",
    domain: "content",
    title: "Be intentional about media use",
    description: "Choose media deliberately instead of defaulting to whatever is easiest.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["content_quality", "addiction"],
    goals: ["better_content"],
    weight: 8,
    isCore: true,
  },
  {
    key: "prioritize_educational_prosocial_positive",
    domain: "content",
    title: "Prioritize creative, educational, prosocial, and positive media",
    description: "Choose slower, higher-quality content aligned with learning and well-being.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["content_quality", "attention"],
    goals: ["better_content"],
    weight: 10,
    isCore: true,
  },
  {
    key: "review_games_before_playing",
    domain: "content",
    title: "Review games together before buying or playing",
    description: "Check content, spending hooks, chat features, and age fit.",
    ageBands: ["6-12", "13-18"],
    concerns: ["gaming", "safety", "overspending"],
    usageTypes: ["gaming"],
    weight: 8,
  },
  {
    key: "plan_online_spending",
    domain: "content",
    title: "Make a plan about spending money online",
    description: "Reduce impulsive purchases and in-app spending.",
    ageBands: ["6-12", "13-18"],
    concerns: ["overspending", "gaming"],
    weight: 7,
  },
  {
    key: "choose_higher_quality_lower_commercial_content",
    domain: "content",
    title: "Choose higher-quality, lower-commercial content",
    description: "Favor slower, more trustworthy, less ad-driven content over noisy, commercialized feeds.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["content_quality", "attention", "social_media"],
    usageTypes: ["short_video", "social_media", "entertainment", "mixed"],
    goals: ["better_content", "safer_media_use"],
    weight: 9,
    isCore: true,
    tags: ["quality", "commercialization"],
  },
  {
    key: "family_experiments_try_keep_uninstall",
    domain: "content",
    title: "Try new shows or apps together and uninstall the ones that are not a good fit",
    description: "Treat media choices as experiments rather than permanent commitments.",
    ageBands: ["0-5", "6-12", "13-18"],
    concerns: ["content_quality"],
    weight: 6,
  },
  {
    key: "plan_family_movie_nights",
    domain: "co_use",
    title: "Plan family movie nights",
    description: "Turn some screen time into shared family time.",
    ageBands: ["0-5", "6-12", "13-18"],
    goals: ["family_connection"],
    weight: 5,
  },
  {
    key: "co_view_to_connect_and_learn",
    domain: "co_use",
    title: "Co-view media to connect and help children learn",
    description: "Use media together and talk about what you see.",
    ageBands: ["0-5", "6-12"],
    concerns: ["content_quality", "attention"],
    goals: ["family_connection", "better_content"],
    weight: 9,
    isCore: true,
  },
  {
    key: "prefer_shared_devices_for_younger_children",
    domain: "co_use",
    title: "Prefer shared devices over solo personal devices for younger children",
    description: "Shared devices make it easier to co-use, supervise, and keep boundaries consistent.",
    ageBands: ["0-5", "6-12"],
    concerns: ["safety", "attention", "addiction"],
    triggers: ["has_personal_device", "low_co_engagement"],
    goals: ["family_connection", "safer_media_use"],
    weight: 8,
    tags: ["shared-device", "co-use"],
  },
  {
    key: "play_games_watch_videos_together",
    domain: "co_use",
    title: "Play apps and games or watch videos together as a family",
    description: "Make digital experiences more relational and less solitary.",
    ageBands: ["0-5", "6-12", "13-18"],
    goals: ["family_connection"],
    weight: 6,
  },
];
